import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import styles from '../styles/Home.module.css'
import Navigator from './components/navigator'
import Home from './home'

interface NavigatorProps {
  name: string
  setName: (n: string) => void
}

const Index: NextPage<NavigatorProps> = (props) => {
  useEffect(() => {
    (
      async () => {
        const response = await fetch('', {
          headers: { 'Content-Type': 'application/json' },
          credentials: 'include',
        })

        const content = await response.json()

        props.setName(content.name)
      }
    )()
  })

  return (
    <div className={styles.App}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home name={props.name} setName={props.setName}/>
      <Navigator name={props.name} setName={props.setName}/>
    </div>
  )
}

export default Index
